// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// xxxxxfirebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_L2cZCv4JiFcMhfj-8F2O6z3Qwc7mCik',
    appId: '1:386752507656:web:cffb86b532dce94114c6bd',
    messagingSenderId: '386752507656',
    projectId: 'celtamobile-7d69a',
    authDomain: 'celtamobile-7d69a.firebaseapp.com',
    databaseURL: 'https://celtamobile-7d69a-default-rtdb.firebaseio.com',
    storageBucket: 'celtamobile-7d69a.appspot.com',
    measurementId: 'G-DCFPPH5WG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwyOVAPIabJ6k65VyyBeTv_wx4vz-pSmc',
    appId: '1:386752507656:android:a6e4e81749987ca914c6bd',
    messagingSenderId: '386752507656',
    projectId: 'celtamobile-7d69a',
    databaseURL: 'https://celtamobile-7d69a-default-rtdb.firebaseio.com',
    storageBucket: 'celtamobile-7d69a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_eAoH_dVzoo3CqZ4ZqRQssyUHRNj2QM',
    appId: '1:386752507656:ios:669a772b9702d2e114c6bd',
    messagingSenderId: '386752507656',
    projectId: 'celtamobile-7d69a',
    databaseURL: 'https://celtamobile-7d69a-default-rtdb.firebaseio.com',
    storageBucket: 'celtamobile-7d69a.appspot.com',
    iosBundleId: 'br.com.celtaware.inventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_L2cZCv4JiFcMhfj-8F2O6z3Qwc7mCik',
    appId: '1:386752507656:web:d5c46600f7b211d814c6bd',
    messagingSenderId: '386752507656',
    projectId: 'celtamobile-7d69a',
    authDomain: 'celtamobile-7d69a.firebaseapp.com',
    databaseURL: 'https://celtamobile-7d69a-default-rtdb.firebaseio.com',
    storageBucket: 'celtamobile-7d69a.appspot.com',
    measurementId: 'G-4V9LLV2FWP',
  );

}