// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcv-Be3sq7SxsbDP1c_aKSUmv4qmtFuvE',
    appId: '1:137101492083:web:0e5919e298b27b5e458f06',
    messagingSenderId: '137101492083',
    projectId: 'celtamobile-ac5b1',
    authDomain: 'celtamobile-ac5b1.firebaseapp.com',
    storageBucket: 'celtamobile-ac5b1.appspot.com',
    measurementId: 'G-NLSFQY8HTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRv_c-QbjFtQb4D92Ij6IXle0i58A0-Bc',
    appId: '1:137101492083:android:f0e50c59299aeff7458f06',
    messagingSenderId: '137101492083',
    projectId: 'celtamobile-ac5b1',
    storageBucket: 'celtamobile-ac5b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmPx8KFlC4KSv7SZpG3zVrAFSXKECTq1A',
    appId: '1:137101492083:ios:2da529507583387b458f06',
    messagingSenderId: '137101492083',
    projectId: 'celtamobile-ac5b1',
    storageBucket: 'celtamobile-ac5b1.appspot.com',
    androidClientId: '137101492083-kk2u32s7va7v0cpvemk36bk8c2g4mslb.apps.googleusercontent.com',
    iosBundleId: 'com.example.celtaInventario',
  );
}
