class APPROUTES {
  static const LOGIN_OR_HOME_PAGE = '/';
  static const ENTERPRISE = '/ENTERPRISE';
  static const PRICE_CONFERENCE = '/PRICE_CONFERENCE';
  static const INVENTORY = '/INVENTORY';
  static const SALES = '/SALES';
  static const STOCK = '/STOCK';
  static const LOGIN_PAGE = '/LOGINPAGE';
  static const COUNTINGS = '/COUNTINGS';
  static const INVENTORY_PRODUCTS = '/INVENTORY_PRODUCTS';
  static const SPLASHPAGE = '/SPLASHPAGE';
  static const HOME_PAGE = '/HOME_PAGE';
  static const RECEIPT = '/RECEIPT';
  static const RECEIPT_CONFERENCE = '/RECEIPT_CONFERENCE';
  static const ADJUST_STOCK = '/ADJUST_STOCK';
  static const TRANSFER_BETWEEN_STOCK = '/TRANSFER_BETWEEN_STOCK';
  static const TRANSFER_BETWEEN_PACKAGE = '/TRANSFER_BETWEEN_PACKAGE';
  static const SALE_REQUEST = '/SALE_REQUEST';
  static const SALE_REQUEST_MODEL = '/SALE_REQUEST_MODEL';
  static const SALE_REQUEST_MANUAL_DEFAULT_REQUEST_MODEL =
      '/SALE_REQUEST_MANUAL_DEFAULT_REQUEST_MODEL';
  static const TRANSFER_REQUEST_MODEL = '/TRANSFER_REQUEST_MODEL';
  static const TRANSFER_ORIGIN_ENTERPRISE = '/TRANSFER_ORIGIN_ENTERPRISE';
  static const TRANSFER_DESTINY_ENTERPRISE = '/TRANSFER_DESTINY_ENTERPRISE';
  static const TRANSFER = '/TRANSFER';
  static const CUSTOMER_REGISTER = '/CUSTOMER_REGISTER';
  static const TECHNICAL_SUPPORT = '/TECHNICAL_SUPPORT';
  static const CONFIGURATIONS = '/CONFIGURATIONS';
  static const BUYERS = '/BUYERS';
  static const RESEARCH_PRICES = '/RESEARCH_PRICES';
  static const RESEARCH_PRICES_INSERT_UPDATE_RESEARCH_PRICE =
      '/RESEARCH_PRICES_INSERT_UPDATE_RESEARCH_PRICE';
  static const RESEARCH_PRICES_CONCURRENTS = '/RESEARCH_PRICES_CONCURRENTS';
  static const RESERACH_PRICE_INSERT_UPDATE_CONCORRENT =
      '/RESERACH_PRICE_INSERT_UPDATE_CONCORRENT';
  static const RESEARCH_PRICES_INSERT_PRICE = '/RESEARCH_PRICES_INSERT_PRICE';
  static const NOTIFICATIONS = '/NOTIFICATIONS';
  static const WEB_LOGIN = '/WEB_LOGIN';
  static const WEB_HOME = '/WEB_HOME';
  static const WEB_ENTERPRISE_DETAILS = '/WEB_ENTERPRISE_DETAILS';
  static const WEB_SOAP_DETAILS = '/WEB_SOAP_DETAILS';
  static const ADJUST_SALE_PRICE = '/ADJUST_SALE_PRICE';
}
